(subdir Sigmalib
 (rocq.extraction
  (prelude Extraction)
  (extracted_files BinInt.ml BinInt.mli BinNat.ml BinNat.mli BinNums.ml BinNums.mli BinPos.ml BinPos.mli Datatypes.ml Datatypes.mli Functions.ml Functions.mli PosDef.ml PosDef.mli Sigma.ml Sigma.mli SigmaIns.ml SigmaIns.mli Specif.ml Specif.mli Vector.ml Vector.mli VectorDef.ml VectorDef.mli Zpstar.ml Zpstar.mli)
  (theories ExtLib Stdlib Utility Crypto Algebra 
   Probability Examples))
 (library 
   (name Sigmalib)
   (libraries zarith)
   (modules :standard)))
 
   
(subdir HeliosTallylib
 (rocq.extraction
  (prelude Extraction)
  (extracted_files Approval.ml Approval.mli Ascii.ml Ascii.mli BinInt.ml BinInt.mli BinNat.ml BinNat.mli BinNums.ml BinNums.mli BinPos.ml BinPos.mli ChaumPedersen.ml ChaumPedersen.mli Datatypes.ml Datatypes.mli DistElgamal.ml DistElgamal.mli Elgamal.ml Elgamal.mli EncProof.ml EncProof.mli EqSigma.ml EqSigma.mli Fin.ml Fin.mli Functions.ml Functions.mli HeliosFrontendIns.ml HeliosFrontendIns.mli HeliosTally.ml HeliosTally.mli HeliosTallyIns.ml HeliosTallyIns.mli Logic.ml Logic.mli Nat.ml Nat.mli PosDef.ml PosDef.mli Sigma.ml Sigma.mli Specif.ml Specif.mli String.ml String.mli Util.ml Util.mli Vector.ml Vector.mli VectorDef.ml VectorDef.mli Zpstar.ml Zpstar.mli)
  (theories ExtLib Stdlib Utility Crypto Algebra 
   Probability Examples Coqprime Bignums Frontend 
   Backend))
 (library 
   (name HeliosTallylib)
   (libraries zarith)
   (modules :standard)))

(subdir ParaSigmalib
 (rocq.extraction
  (prelude Extraction)
  (extracted_files BinInt.ml BinInt.mli BinNat.ml BinNat.mli BinNums.ml BinNums.mli BinPos.ml BinPos.mli Datatypes.ml Datatypes.mli Functions.ml Functions.mli Logic.ml Logic.mli Nat.ml Nat.mli ParaSigmaIns.ml ParaSigmaIns.mli ParallelSigma.ml ParallelSigma.mli PosDef.ml PosDef.mli Sigma.ml Sigma.mli Specif.ml Specif.mli Util.ml Util.mli Vector.ml Vector.mli VectorDef.ml VectorDef.mli Zpstar.ml Zpstar.mli)
  (theories ExtLib Stdlib Utility Crypto Algebra 
   Probability Examples))
 (library 
   (name ParaSigmalib)
   (libraries zarith)
   (modules :standard)))

(subdir AndSigmalib
 (rocq.extraction
  (prelude Extraction)
  (extracted_files AndSigma.ml AndSigma.mli AndSigmaIns.ml AndSigmaIns.mli BinInt.ml BinInt.mli BinNat.ml BinNat.mli BinNums.ml BinNums.mli BinPos.ml BinPos.mli Datatypes.ml Datatypes.mli Functions.ml Functions.mli Logic.ml Logic.mli Nat.ml Nat.mli PosDef.ml PosDef.mli Sigma.ml Sigma.mli Specif.ml Specif.mli Util.ml Util.mli Vector.ml Vector.mli VectorDef.ml VectorDef.mli Zpow_facts.ml Zpow_facts.mli Zpstar.ml Zpstar.mli)
  (theories ExtLib Stdlib Utility Crypto Algebra 
   Probability Examples))
 (library 
   (name AndSigmalib)
   (libraries zarith)
   (modules :standard)))

(subdir Elgamallib
 (rocq.extraction
  (prelude Extraction)
  (extracted_files BinInt.ml BinInt.mli BinNat.ml BinNat.mli BinNums.ml BinNums.mli BinPos.ml BinPos.mli Datatypes.ml Datatypes.mli Elgamal.ml Elgamal.mli ElgamalIns.ml ElgamalIns.mli Functions.ml Functions.mli Logic.ml Logic.mli PosDef.ml PosDef.mli Util.ml Util.mli Vector.ml Vector.mli VectorDef.ml VectorDef.mli Zpstar.ml Zpstar.mli)
  (theories ExtLib Stdlib Utility Crypto Algebra 
   Probability Examples))
 (library 
   (name Elgamallib)
   (libraries zarith)
   (modules :standard)))

(subdir DistElgamallib
 (rocq.extraction
  (prelude Extraction)
  (extracted_files BinInt.ml BinInt.mli BinNat.ml BinNat.mli BinNums.ml BinNums.mli BinPos.ml BinPos.mli Datatypes.ml Datatypes.mli DistElgamal.ml DistElgamal.mli DistElgamalIns.ml DistElgamalIns.mli Elgamal.ml Elgamal.mli Functions.ml Functions.mli Logic.ml Logic.mli Nat.ml Nat.mli PosDef.ml PosDef.mli Specif.ml Specif.mli Util.ml Util.mli Vector.ml Vector.mli VectorDef.ml VectorDef.mli Zpstar.ml Zpstar.mli)
  (theories ExtLib Stdlib Utility Crypto Algebra 
   Probability Examples))
 (library 
   (name DistElgamallib)
   (libraries zarith)
   (modules :standard)))

(subdir OrSigmalib
 (rocq.extraction
  (prelude Extraction)
  (extracted_files BinInt.ml BinInt.mli BinNat.ml BinNat.mli BinNums.ml BinNums.mli BinPos.ml BinPos.mli Datatypes.ml Datatypes.mli Fin.ml Fin.mli Functions.ml Functions.mli Logic.ml Logic.mli Nat.ml Nat.mli OrSigma.ml OrSigma.mli OrSigmaIns.ml OrSigmaIns.mli PosDef.ml PosDef.mli Sigma.ml Sigma.mli Specif.ml Specif.mli Util.ml Util.mli Vector.ml Vector.mli VectorDef.ml VectorDef.mli Zpstar.ml Zpstar.mli)
  (theories ExtLib Stdlib Utility Crypto Algebra 
   Probability Examples))
 (library 
   (name OrSigmalib)
   (libraries zarith)
   (modules :standard)))

(subdir EncProoflib
 (rocq.extraction
  (prelude Extraction)
  (extracted_files BinInt.ml BinInt.mli BinNat.ml BinNat.mli BinNums.ml BinNums.mli BinPos.ml BinPos.mli Datatypes.ml Datatypes.mli EncProof.ml EncProof.mli EncProofIns.ml EncProofIns.mli Fin.ml Fin.mli Functions.ml Functions.mli Logic.ml Logic.mli Nat.ml Nat.mli PosDef.ml PosDef.mli Sigma.ml Sigma.mli Specif.ml Specif.mli Util.ml Util.mli Vector.ml Vector.mli VectorDef.ml VectorDef.mli Zpstar.ml Zpstar.mli)
  (theories ExtLib Stdlib Utility Crypto Algebra 
   Probability Examples))
 (library 
   (name EncProoflib)
   (libraries zarith)
   (modules :standard)))

(subdir EqSigmalib
 (rocq.extraction
  (prelude Extraction)
  (extracted_files BinInt.ml BinInt.mli BinNat.ml BinNat.mli BinNums.ml BinNums.mli BinPos.ml BinPos.mli Datatypes.ml Datatypes.mli EqSigma.ml EqSigma.mli EqSigmaIns.ml EqSigmaIns.mli Functions.ml Functions.mli Nat.ml Nat.mli PosDef.ml PosDef.mli Sigma.ml Sigma.mli Specif.ml Specif.mli Util.ml Util.mli Vector.ml Vector.mli VectorDef.ml VectorDef.mli Zpstar.ml Zpstar.mli)
  (theories ExtLib Stdlib Utility Crypto Algebra 
   Probability Examples))
 (library 
   (name EqSigmalib)
   (libraries zarith)
   (modules :standard)))

(subdir Approvallib
 (rocq.extraction
  (prelude Extraction)
  (extracted_files Approval.ml Approval.mli ApprovalIns.ml ApprovalIns.mli BinInt.ml BinInt.mli BinNat.ml BinNat.mli BinNums.ml BinNums.mli BinPos.ml BinPos.mli Datatypes.ml Datatypes.mli Elgamal.ml Elgamal.mli EncProof.ml EncProof.mli Fin.ml Fin.mli Functions.ml Functions.mli Logic.ml Logic.mli Nat.ml Nat.mli PosDef.ml PosDef.mli Sigma.ml Sigma.mli Specif.ml Specif.mli Util.ml Util.mli Vector.ml Vector.mli VectorDef.ml VectorDef.mli Zpstar.ml Zpstar.mli)
  (theories ExtLib Stdlib Utility Crypto Algebra 
   Probability Examples Frontend))
 (library 
   (name Approvallib)
   (libraries zarith)
   (modules :standard)))

(subdir Tallylib
 (rocq.extraction
  (prelude Extraction)
  (extracted_files Approval.ml Approval.mli BinInt.ml BinInt.mli BinNat.ml BinNat.mli BinNums.ml BinNums.mli BinPos.ml BinPos.mli ChaumPedersen.ml ChaumPedersen.mli Datatypes.ml Datatypes.mli DecProof.ml DecProof.mli Elgamal.ml Elgamal.mli EncProof.ml EncProof.mli EqSigma.ml EqSigma.mli Functions.ml Functions.mli Logic.ml Logic.mli Nat.ml Nat.mli PosDef.ml PosDef.mli Sigma.ml Sigma.mli Specif.ml Specif.mli Tally.ml Tally.mli TallyIns.ml TallyIns.mli Util.ml Util.mli Vector.ml Vector.mli VectorDef.ml VectorDef.mli Zpstar.ml Zpstar.mli)
  (theories ExtLib Stdlib Utility Crypto Algebra 
   Probability Examples Frontend Backend))
 (library 
   (name Tallylib)
   (libraries zarith)
   (modules :standard)))

(subdir ChaumPedersenlib
 (rocq.extraction
  (prelude Extraction)
  (extracted_files BinInt.ml BinInt.mli BinNat.ml BinNat.mli BinNums.ml BinNums.mli BinPos.ml BinPos.mli ChaumPedersen.ml ChaumPedersen.mli ChaumPedersenIns.ml ChaumPedersenIns.mli Datatypes.ml Datatypes.mli EqSigma.ml EqSigma.mli Functions.ml Functions.mli Nat.ml Nat.mli PosDef.ml PosDef.mli Sigma.ml Sigma.mli Specif.ml Specif.mli Util.ml Util.mli Vector.ml Vector.mli VectorDef.ml VectorDef.mli Zpstar.ml Zpstar.mli)
  (theories ExtLib Stdlib Utility Crypto Algebra 
   Probability Examples Frontend Backend))
 (library 
   (name ChaumPedersenlib)
   (libraries zarith)
   (modules :standard)))

(subdir NeqSigmalib
 (rocq.extraction
  (prelude Extraction)
  (extracted_files AndSigmaGen.ml AndSigmaGen.mli BinInt.ml BinInt.mli BinNat.ml BinNat.mli BinNums.ml BinNums.mli BinPos.ml BinPos.mli Datatypes.ml Datatypes.mli Functions.ml Functions.mli Logic.ml Logic.mli Nat.ml Nat.mli NeqSigma.ml NeqSigma.mli NeqSigmaIns.ml NeqSigmaIns.mli Okamoto.ml Okamoto.mli PeanoNat.ml PeanoNat.mli PosDef.ml PosDef.mli Sigma.ml Sigma.mli Specif.ml Specif.mli Util.ml Util.mli Vector.ml Vector.mli VectorDef.ml VectorDef.mli Zpow_facts.ml Zpow_facts.mli Zpstar.ml Zpstar.mli)
  (theories ExtLib Stdlib Utility Crypto Algebra 
   Probability Examples Frontend Backend))
 (library 
   (name NeqSigmalib)
   (libraries zarith)
   (modules :standard)))

(subdir PedLinearRellib
 (rocq.extraction
  (prelude Extraction)
  (extracted_files BinInt.ml BinInt.mli BinNat.ml BinNat.mli BinNums.ml BinNums.mli BinPos.ml BinPos.mli Datatypes.ml Datatypes.mli Functions.ml Functions.mli Logic.ml Logic.mli Nat.ml Nat.mli PedLinearRel.ml PedLinearRel.mli PedLinearRelIns.ml PedLinearRelIns.mli PosDef.ml PosDef.mli Sigma.ml Sigma.mli Specif.ml Specif.mli Util.ml Util.mli Vector.ml Vector.mli VectorDef.ml VectorDef.mli Zpstar.ml Zpstar.mli)
  (theories ExtLib Stdlib Utility Crypto Algebra 
   Probability Examples Frontend Backend))
 (library 
   (name PedLinearRellib)
   (libraries zarith)
   (modules :standard)))
