(subdir Sigmalib
 (rocq.extraction
  (prelude Extraction)
  (extracted_files SigmaIns.ml SigmaIns.mli Sigma.ml Sigma.mli Datatypes.ml Datatypes.mli Vector.ml Vector.mli VectorDef.ml VectorDef.mli Zpstar.ml Zpstar.mli BinInt.ml BinInt.mli PosDef.ml PosDef.mli Functions.ml Functions.mli BinNat.ml BinNat.mli Specif.ml Specif.mli)
  (theories ExtLib Stdlib Utility Crypto Algebra 
   Probability Examples))
 (library 
   (name Sigmalib)
   (libraries zarith)
   (modules :standard)))
 
   
(subdir HeliosTallylib
 (rocq.extraction
  (prelude Extraction)
  (extracted_files HeliosTallyIns.ml HeliosTallyIns.mli HeliosFrontendIns.ml HeliosFrontendIns.mli HeliosTally.ml HeliosTally.mli Sigma.ml Sigma.mli Datatypes.ml Datatypes.mli Vector.ml Vector.mli Fin.ml Fin.mli VectorDef.ml VectorDef.mli Zpstar.ml Zpstar.mli BinInt.ml BinInt.mli PosDef.ml PosDef.mli Functions.ml Functions.mli BinNat.ml BinNat.mli Approval.ml Approval.mli EncProof.ml EncProof.mli Specif.ml Specif.mli Util.ml Util.mli EqdepFacts.ml EqdepFacts.mli ChaumPedersen.ml ChaumPedersen.mli EqSigma.ml EqSigma.mli DistElgamal.ml DistElgamal.mli Elgamal.ml Elgamal.mli Nat.ml Nat.mli)
  (theories ExtLib Stdlib Utility Crypto Algebra 
   Probability Examples Coqprime Bignums Frontend 
   Backend))
 (library 
   (name HeliosTallylib)
   (libraries zarith)
   (modules :standard)))

(subdir ParaSigmalib
 (rocq.extraction
  (prelude Extraction)
  (extracted_files ParaSigmaIns.ml ParaSigmaIns.mli ParallelSigma.ml ParallelSigma.mli Sigma.ml Sigma.mli Datatypes.ml Datatypes.mli Vector.ml Vector.mli VectorDef.ml VectorDef.mli Zpstar.ml Zpstar.mli BinInt.ml BinInt.mli PosDef.ml PosDef.mli Functions.ml Functions.mli BinNat.ml BinNat.mli Specif.ml Specif.mli Util.ml Util.mli EqdepFacts.ml EqdepFacts.mli Nat.ml Nat.mli)
  (theories ExtLib Stdlib Utility Crypto Algebra 
   Probability Examples))
 (library 
   (name ParaSigmalib)
   (libraries zarith)
   (modules :standard)))

(subdir AndSigmalib
 (rocq.extraction
  (prelude Extraction)
  (extracted_files AndSigmaIns.ml AndSigmaIns.mli AndSigma.ml AndSigma.mli Sigma.ml Sigma.mli Zpow_facts.ml Zpow_facts.mli Datatypes.ml Datatypes.mli Vector.ml Vector.mli VectorDef.ml VectorDef.mli Zpstar.ml Zpstar.mli BinInt.ml BinInt.mli PosDef.ml PosDef.mli Functions.ml Functions.mli BinNat.ml BinNat.mli Specif.ml Specif.mli Util.ml Util.mli EqdepFacts.ml EqdepFacts.mli Nat.ml Nat.mli)
  (theories ExtLib Stdlib Utility Crypto Algebra 
   Probability Examples))
 (library 
   (name AndSigmalib)
   (libraries zarith)
   (modules :standard)))

(subdir Elgamallib
 (rocq.extraction
  (prelude Extraction)
  (extracted_files Elgamal.ml Elgamal.mli ElgamalIns.ml ElgamalIns.mli Datatypes.ml Datatypes.mli Vector.ml Vector.mli VectorDef.ml VectorDef.mli Zpstar.ml Zpstar.mli BinInt.ml BinInt.mli PosDef.ml PosDef.mli Functions.ml Functions.mli BinNat.ml BinNat.mli Util.ml Util.mli EqdepFacts.ml EqdepFacts.mli)
  (theories ExtLib Stdlib Utility Crypto Algebra 
   Probability Examples))
 (library 
   (name Elgamallib)
   (libraries zarith)
   (modules :standard)))

(subdir DistElgamallib
 (rocq.extraction
  (prelude Extraction)
  (extracted_files Elgamal.ml Elgamal.mli DistElgamal.ml DistElgamal.mli DistElgamalIns.ml DistElgamalIns.mli Datatypes.ml Datatypes.mli Vector.ml Vector.mli VectorDef.ml VectorDef.mli Zpstar.ml Zpstar.mli BinInt.ml BinInt.mli PosDef.ml PosDef.mli Functions.ml Functions.mli BinNat.ml BinNat.mli Util.ml Util.mli EqdepFacts.ml EqdepFacts.mli Specif.ml Specif.mli Nat.ml Nat.mli)
  (theories ExtLib Stdlib Utility Crypto Algebra 
   Probability Examples))
 (library 
   (name DistElgamallib)
   (libraries zarith)
   (modules :standard)))

(subdir OrSigmalib
 (rocq.extraction
  (prelude Extraction)
  (extracted_files OrSigmaIns.ml OrSigmaIns.mli OrSigma.ml OrSigma.mli Datatypes.ml Datatypes.mli Vector.ml Vector.mli Nat.ml Nat.mli Fin.ml Fin.mli Specif.ml Specif.mli Sigma.ml Sigma.mli VectorDef.ml VectorDef.mli Zpstar.ml Zpstar.mli BinInt.ml BinInt.mli PosDef.ml PosDef.mli Functions.ml Functions.mli BinNat.ml BinNat.mli Util.ml Util.mli EqdepFacts.ml EqdepFacts.mli)
  (theories ExtLib Stdlib Utility Crypto Algebra 
   Probability Examples))
 (library 
   (name OrSigmalib)
   (libraries zarith)
   (modules :standard)))

(subdir EncProoflib
 (rocq.extraction
  (prelude Extraction)
  (extracted_files EncProofIns.ml EncProofIns.mli EncProof.ml EncProof.mli Datatypes.ml Datatypes.mli Vector.ml Vector.mli Nat.ml Nat.mli Fin.ml Fin.mli Specif.ml Specif.mli Sigma.ml Sigma.mli VectorDef.ml VectorDef.mli Zpstar.ml Zpstar.mli BinInt.ml BinInt.mli PosDef.ml PosDef.mli Functions.ml Functions.mli BinNat.ml BinNat.mli Util.ml Util.mli EqdepFacts.ml EqdepFacts.mli)
  (theories ExtLib Stdlib Utility Crypto Algebra 
   Probability Examples))
 (library 
   (name EncProoflib)
   (libraries zarith)
   (modules :standard)))

(subdir EqSigmalib
 (rocq.extraction
  (prelude Extraction)
  (extracted_files EqSigmaIns.ml EqSigmaIns.mli EqSigma.ml EqSigma.mli Datatypes.ml Datatypes.mli Vector.ml Vector.mli Nat.ml Nat.mli Specif.ml Specif.mli Sigma.ml Sigma.mli VectorDef.ml VectorDef.mli Zpstar.ml Zpstar.mli BinInt.ml BinInt.mli PosDef.ml PosDef.mli Functions.ml Functions.mli BinNat.ml BinNat.mli Util.ml Util.mli)
  (theories ExtLib Stdlib Utility Crypto Algebra 
   Probability Examples))
 (library 
   (name EqSigmalib)
   (libraries zarith)
   (modules :standard)))

(subdir Approvallib
 (rocq.extraction
  (prelude Extraction)
  (extracted_files ApprovalIns.ml ApprovalIns.mli Approval.ml Approval.mli EncProof.ml EncProof.mli Datatypes.ml Datatypes.mli Vector.ml Vector.mli Nat.ml Nat.mli Specif.ml Specif.mli Sigma.ml Sigma.mli VectorDef.ml VectorDef.mli Zpstar.ml Zpstar.mli BinInt.ml BinInt.mli PosDef.ml PosDef.mli Functions.ml Functions.mli BinNat.ml BinNat.mli Util.ml Util.mli EqdepFacts.ml EqdepFacts.mli Fin.ml Fin.mli Elgamal.ml Elgamal.mli)
  (theories ExtLib Stdlib Utility Crypto Algebra 
   Probability Examples Frontend))
 (library 
   (name Approvallib)
   (libraries zarith)
   (modules :standard)))


(subdir Tallylib
 (rocq.extraction
  (prelude Extraction)
  (extracted_files TallyIns.ml TallyIns.mli Tally.ml Tally.mli Approval.ml Approval.mli EncProof.ml EncProof.mli DecProof.ml DecProof.mli ChaumPedersen.ml ChaumPedersen.mli EqSigma.ml EqSigma.mli Datatypes.ml Datatypes.mli Vector.ml Vector.mli Nat.ml Nat.mli Specif.ml Specif.mli Sigma.ml Sigma.mli VectorDef.ml VectorDef.mli Zpstar.ml Zpstar.mli BinInt.ml BinInt.mli PosDef.ml PosDef.mli Functions.ml Functions.mli BinNat.ml BinNat.mli Util.ml Util.mli EqdepFacts.ml EqdepFacts.mli Elgamal.ml Elgamal.mli)
  (theories ExtLib Stdlib Utility Crypto Algebra 
   Probability Examples Frontend Backend))
 (library 
   (name Tallylib)
   (libraries zarith)
   (modules :standard)))



(subdir ChaumPedersenlib
 (rocq.extraction
  (prelude Extraction)
  (extracted_files ChaumPedersenIns.ml ChaumPedersenIns.mli ChaumPedersen.ml ChaumPedersen.mli EqSigma.ml EqSigma.mli Datatypes.ml Datatypes.mli Vector.ml Vector.mli Nat.ml Nat.mli Specif.ml Specif.mli Sigma.ml Sigma.mli VectorDef.ml VectorDef.mli Zpstar.ml Zpstar.mli BinInt.ml BinInt.mli PosDef.ml PosDef.mli Functions.ml Functions.mli BinNat.ml BinNat.mli Util.ml Util.mli)
  (theories ExtLib Stdlib Utility Crypto Algebra 
   Probability Examples Frontend Backend))
 (library 
   (name ChaumPedersenlib)
   (libraries zarith)
   (modules :standard)))

(subdir NeqSigmalib
 (rocq.extraction
  (prelude Extraction)
  (extracted_files NeqSigmaIns.ml NeqSigmaIns.mli Okamoto.ml Okamoto.mli NeqSigma.ml NeqSigma.mli Datatypes.ml Datatypes.mli Vector.ml Vector.mli Nat.ml Nat.mli Specif.ml Specif.mli Sigma.ml Sigma.mli VectorDef.ml VectorDef.mli Zpstar.ml Zpstar.mli BinInt.ml BinInt.mli PosDef.ml PosDef.mli Functions.ml Functions.mli BinNat.ml BinNat.mli Util.ml Util.mli EqdepFacts.ml EqdepFacts.mli AndSigmaGen.ml AndSigmaGen.mli PeanoNat.ml PeanoNat.mli Zpow_facts.ml Zpow_facts.mli)
  (theories ExtLib Stdlib Utility Crypto Algebra 
   Probability Examples Frontend Backend))
 (library 
   (name NeqSigmalib)
   (libraries zarith)
   (modules :standard)))

(subdir PedLinearRellib
 (rocq.extraction
  (prelude Extraction)
  (extracted_files PedLinearRelIns.ml PedLinearRelIns.mli PedLinearRel.ml PedLinearRel.mli Datatypes.ml Datatypes.mli Vector.ml Vector.mli Nat.ml Nat.mli Sigma.ml Sigma.mli VectorDef.ml VectorDef.mli Zpstar.ml Zpstar.mli BinInt.ml BinInt.mli PosDef.ml PosDef.mli Functions.ml Functions.mli BinNat.ml BinNat.mli Util.ml Util.mli EqdepFacts.ml EqdepFacts.mli)
  (theories ExtLib Stdlib Utility Crypto Algebra 
   Probability Examples Frontend Backend))
 (library 
   (name PedLinearRellib)
   (libraries zarith)
   (modules :standard)))